In [ ]:
import torch
dim = 8
seq_len = 100
theta = 10000

freqs = 1.0 / (theta ** (torch.arange(0, dim, 2)[: (dim // 2)].float() / dim))
# 生成 token 序列索引 t = [0, 1,..., seq_len-1]
t = torch.arange(seq_len, device=freqs.device)
# freqs.shape = [seq_len, dim // 2] 
freqs = torch.outer(t, freqs).float()  # 计算m * \theta input 和 vec2 的外积。如果 input 是大小为 n 的向量，而 vec2 是大小为 m 的向量，则 out 必须是大小为 (n×m) 的矩阵。不可广播

# 计算结果是个复数向量
# 假设 freqs = [x, y]
# 则 freqs_cis = [cos(x) + sin(x)i, cos(y) + sin(y)i]
freqs_cis = torch.polar(torch.ones_like(freqs), freqs) # 极坐标

In [1]:
print(-1e-9)

-1e-09


In [2]:
m = 3
n = 5
dp = [[1] * n] + [[1] + [0] * (n - 1) for _ in range(m-1)]
print(dp)


[[1, 1, 1, 1, 1], [1, 0, 0, 0, 0], [1, 0, 0, 0, 0]]


AttributeError: 'list' object has no attribute 'shape'

In [2]:
import torch.distributed as dist
import os

dist.init_process_group(backend='nccl', rank=0)
print(dist.get_rank())

d:\anaconda3\envs\pytorch\lib\site-packages\torch\distributed\distributed_c10d.py:608: UserWarning: Attempted to get default timeout for nccl backend, but NCCL support is not compiled
  warnings.warn("Attempted to get default timeout for nccl backend, but NCCL support is not compiled")


ValueError: Error initializing torch.distributed using env:// rendezvous: environment variable WORLD_SIZE expected, but not set

In [1]:
import torch
w_values = [
        [0.2, 0.9, 0.7, 0.7],
        [0.5, 0.2, 0.6, 0.0],
        [0.1, 0.2, 0.8, 0.8],
        [0.3, 0.5, 0.8, 1.0],
        [0.7, 0.6, 0.8, 0.2],
        [0.6, 0.1, 0.2, 0.2],
        [0.7, 0.7, 0.2, 0.7],
        [0.8, 0.4, 0.5, 0.6],
        [0.8, 1.0, 0.1, 0.3],
        [0.7, 0.9, 0.9, 0.9],
    ]
w = torch.tensor(w_values, requires_grad=True)

print(w.shape)

sub_w = torch.split(w, [2, 2], dim=1)

print(sub_w)


torch.Size([10, 4])
(tensor([[0.2000, 0.9000],
        [0.5000, 0.2000],
        [0.1000, 0.2000],
        [0.3000, 0.5000],
        [0.7000, 0.6000],
        [0.6000, 0.1000],
        [0.7000, 0.7000],
        [0.8000, 0.4000],
        [0.8000, 1.0000],
        [0.7000, 0.9000]], grad_fn=<SplitWithSizesBackward0>), tensor([[0.7000, 0.7000],
        [0.6000, 0.0000],
        [0.8000, 0.8000],
        [0.8000, 1.0000],
        [0.8000, 0.2000],
        [0.2000, 0.2000],
        [0.2000, 0.7000],
        [0.5000, 0.6000],
        [0.1000, 0.3000],
        [0.9000, 0.9000]], grad_fn=<SplitWithSizesBackward0>))


In [2]:
x = torch.rand(4, 6)
print(x)

tensor([[0.9883, 0.5427, 0.8878, 0.8828, 0.7226, 0.6405],
        [0.9407, 0.0168, 0.6099, 0.6709, 0.5025, 0.3553],
        [0.8024, 0.0245, 0.2826, 0.6800, 0.9657, 0.4073],
        [0.3605, 0.6188, 0.5342, 0.1723, 0.7519, 0.0761]])


In [3]:
import datasets
dataset = datasets.load_dataset("tatoeba", lang1="en", lang2="he")
print(dataset)

d:\anaconda3\envs\pytorch\lib\site-packages\datasets\load.py:1486: FutureWarning: The repository for tatoeba contains custom code which must be executed to correctly load the dataset. You can inspect the repository content at https://hf.co/datasets/tatoeba
You can avoid this message in future by passing the argument `trust_remote_code=True`.
Passing `trust_remote_code=True` will be mandatory to load this dataset from the next major release of `datasets`.
  warnings.warn(


DatasetDict({
    train: Dataset({
        features: ['id', 'translation'],
        num_rows: 164106
    })
})


: 

In [3]:
import torch
'''
mask的作用主要是将mask为true的地方变为负无穷,不影响后续softmax的计算
'''
weight = torch.rand((10,20,30))
mask = torch.ones_like(weight, dtype=torch.bool).triu(1) # 上三角
weight.masked_fill_(mask, -torch.inf)

print(weight)
print(mask)
print(weight)

tensor([[[0.5971,   -inf,   -inf,  ...,   -inf,   -inf,   -inf],
         [0.7396, 0.7678,   -inf,  ...,   -inf,   -inf,   -inf],
         [0.9596, 0.1429, 0.3495,  ...,   -inf,   -inf,   -inf],
         ...,
         [0.6931, 0.5104, 0.8416,  ...,   -inf,   -inf,   -inf],
         [0.9469, 0.1531, 0.1306,  ...,   -inf,   -inf,   -inf],
         [0.2225, 0.8480, 0.2297,  ...,   -inf,   -inf,   -inf]],

        [[0.5997,   -inf,   -inf,  ...,   -inf,   -inf,   -inf],
         [0.2398, 0.3995,   -inf,  ...,   -inf,   -inf,   -inf],
         [0.2111, 0.0847, 0.5076,  ...,   -inf,   -inf,   -inf],
         ...,
         [0.1442, 0.5027, 0.7396,  ...,   -inf,   -inf,   -inf],
         [0.0456, 0.7592, 0.3343,  ...,   -inf,   -inf,   -inf],
         [0.5656, 0.5668, 0.4795,  ...,   -inf,   -inf,   -inf]],

        [[0.6373,   -inf,   -inf,  ...,   -inf,   -inf,   -inf],
         [0.9611, 0.8436,   -inf,  ...,   -inf,   -inf,   -inf],
         [0.0657, 0.0516, 0.7059,  ...,   -inf,   -inf,   